image: registry.scader.eu/docker/docker-homepage:latest

stages:
- build
- deploy

variables:
  FTP_HOST: www138.your-server.de

build:
  stage: build
  script:
  - hugo
  - test -f public/index.html
  artifacts:
    expire_in: 90d
    paths:
    - public

.deploy-job: &deploy-job
  stage: deploy
  script:
  - lftp -c "set ftps:initial-prot ''; set ftp:ssl-force true; set ftp:ssl-protect-data true; open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:21; mirror -eRv public $FTP_ENV; quit;"

.cleanup-job: &cleanup-job
  stage: deploy
  when: manual
  script:
  - lftp -c "set ftps:initial-prot ''; set ftp:ssl-force true; set ftp:ssl-protect-data true; open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:21; rm -r $FTP_ENV; mkdir $FTP_ENV; quit;"

deploy to development:
  <<: *deploy-job
  when: manual
  variables:
    FTP_ENV: dev
  environment:
    name: development
    url: https://dev.sidorenko.io
    on_stop: cleanup development

cleanup development:
  <<: *cleanup-job
  variables:
    FTP_ENV: dev
  environment:
    name: development
    action: stop

deploy to production:
  <<: *deploy-job
  only:
  - master
  variables:
    FTP_ENV: dev
  environment:
    name: development
    url: https://dev.sidorenko.io
