baseurl       = "/"
title         = "Artem Sidorenko"
relativeURLs  = true
theme         = "bootstrap-premium"
paginate      = 5
copyright     = "Artem Sidorenko"

[permalinks]
  post = "/:year/:month/:title/"
  code = "/:slug/"

[taxonomies]
tag = "tags"

[author]
  name = "Artem Sidorenko"
  email = "artem@posteo.de"

[params]
switchlang = false
showRightSidebar = true
BrandImage = ""
footline = "Powered by [hugo](http://gohugo.io/) with customized [bootstrap-premium](https://github.com/appernetic/hugo-bootstrap-premium/) theme"
mailmunchid = ""
sumomeid = ""
mathjax = ""
googleplus = ""
twitter = ""

[params.theme]
name = "default"

[menu]
  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/"
  weight     = 1

  [[menu.main]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/artem-sidorenko"
  weight     = 9

  [[menu.main]]
  identifier = "rss"
  name       = "RSS"
  url        = "/post/index.xml"
  weight     = 10
