baseurl         = "https://www.sidorenko.io"
title           = "Artem Sidorenko"
theme           = "bootstrap-premium"
paginate        = 10
copyright       = "Artem Sidorenko"
DisqusShortname = "2realities"
enableRobotsTXT = true

[permalinks]
  post = "/:section/:year/:month/:title/"

[taxonomies]
tag = "tags"

[author]
  name = "Artem Sidorenko"

[params]
description = "Blog of Artem Sidorenko"
paginate_sections = 20
switchlang = false
showRightSidebar = true
BrandImage = ""
footline = "Powered by [hugo](http://gohugo.io/) with customized [bootstrap-premium](https://github.com/appernetic/hugo-bootstrap-premium/) theme"
mailmunchid = ""
sumomeid = ""
mathjax = ""
googleplus = ""
twitter = "art_sidorenko"

[params.theme]
name = "default"

[menu]
  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/"
  weight     = 1

  [[menu.main]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/artem-sidorenko"
  weight     = 9

  [[menu.main]]
  identifier = "rss"
  name       = "RSS"
  url        = "/post/index.xml"
  weight     = 10
